development:
  user: fedoraAdmin
  password: <%= ENV["SCHOLAR_FEDORA_PASSWORD"] %>
  url: <%= ENV["SCHOLAR_FEDORA_URL"] %>
>>>>>>> develop
  base_path: /dev
test:
  user: fedoraAdmin
  password: <%= ENV["SCHOLAR_FEDORA_PASSWORD"] %>
  url: <%= ENV["SCHOLAR_FEDORA_URL"] %>
  base_path: /test
production:
  user: fedoraAdmin
  password: <%= ENV["SCHOLAR_FEDORA_PASSWORD"] %>
  url: <%= ENV["SCHOLAR_FEDORA_URL"] %>
  base_path: /prod
