GenericWork:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - license
  - publisher
  - date_created
  - alternate_title
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Article:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - license
  - publisher
  - date_created
  - alternate_title
  - journal_title
  - issn
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Document:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - license
  - publisher
  - date_created
  - alternate_title
  - genre
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Dataset:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - required_software
  - license
  - publisher
  - date_created
  - alternate_title
  - subject
  - geo_subject
  - time_period
  - language
  - note
  - related_url
  - doi
FileSet:
  - id
  - title
  - creator
  - depositor
  - description
  - license
  - publisher
  - date_created
  - subject
  - language
Image:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - license
  - publisher
  - date_created
  - alternate_title
  - genre
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Medium:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - license
  - publisher
  - date_created
  - alternate_title
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Etd:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - advisor
  - license
  - committee_member
  - degree
  - date_created
  - etd_publisher
  - alternate_title
  - genre
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
StudentWork:
  - id
  - title
  - creator
  - depositor
  - description
  - college
  - department
  - advisor
  - license
  - degree
  - publisher
  - date_created
  - alternate_title
  - genre
  - subject
  - geo_subject
  - time_period
  - language
  - required_software
  - note
  - related_url
  - doi
Collection:
  - id
  - title
  - creator
  - depositor
  - description
  - license
