# stores ReCaptcha image server url

development:
  site_key:   <%= ENV["SCHOLAR_CAPTCHA_SITE_KEY"] %>
  secret_key: <%= ENV["SCHOLAR_CAPTCHA_SECRET_KEY"] %>
test:
  site_key:   <%= ENV["SCHOLAR_CAPTCHA_SITE_KEY"] %>
  secret_key: <%= ENV["SCHOLAR_CAPTCHA_SECRET_KEY"] %>
production:
  site_key:   <%= ENV["SCHOLAR_CAPTCHA_SITE_KEY"] %>
  secret_key: <%= ENV["SCHOLAR_CAPTCHA_SECRET_KEY"] %>
