# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV["SCHOLAR_SOLR_URL"] %>
test:
  url: <%= ENV["SCHOLAR_SOLR_URL"] %>
production:
  url: <%= ENV["SCHOLAR_SOLR_URL"] %>
